### PR TITLE
Add basic tests for all scripts

### PR DESCRIPTION
**Pull request by bertfrees**
This PR is part of https://github.com/daisy/pipeline/pull/504

Depends on:
- [x] https://github.com/daisy/pipeline-scripts/pull/98
- [ ] https://github.com/daisy/pipeline-build-utils/pull/33

### CODE REVIEW

**Comment by bertfrees** [comment]
Please wait with merging this, I would like to add a fixup for 3d7e33a.

**Comment by bertfrees** [comment]
@rdeltour Could you maybe try to run the tests on your computer? I am getting strange behavior in several modules: surefire will "disconnect" from the forked process that is created to run the tests in and fails with the message "The forked VM terminated without properly saying goodbye" (see also https://maven.apache.org/surefire/maven-surefire-plugin/faq.html). The process does not crash, you can tell because if you wait a bit, the target/xprocspec-reports/index.html file is created which means the test suite has finished. It doesn't happen consistently, but I've seen this happen with most of the scripts, and also some utility modules. Strangely enough it never happens with the braille modules.

I'm curious whether this happens too on your machine.

**Comment by rdeltour** [comment]
> @rdeltour Could you maybe try to run the tests on your computer?

Can do, but I will have to checkout and compile all the requires PRs of the other repos first. Or is there an easier option with the meta project?

**Comment by bertfrees** [comment]
Yes, I'm afraid it's the only way to do it. It has always been like this. In this case it should be OK though because the only dependency is https://github.com/daisy/pipeline-build-utils/pull/33.

Yesterday I was thinking about creating additional branches in the super-repo to reflect PRs in sub-repos. This would make the amount of work smaller for the reviewer(s) (you would only have to do one checkout) but it would increase the amount of work for the PR creator, so unless I make some scripts to make it automatic it's a bit of a zero sum game.

**Comment by bertfrees** [comment]
Shall I work on a little script to help automate this?

**Comment by bertfrees** [comment]
@rdeltour I have managed to resolve the "disconnect" issue switching to a different test runner (pax-exam-native-container instead of pax-exam-forked-container).

**Comment by bertfrees** [comment]
Fixed in 0772d18.

**Pull request merged**
