### PR TITLE
Check if the element is among the descendants in moveout

### PR DESCRIPTION
**Pull request by capitancambio**
This increases the speed of the algorithm quite dramatically but this is my first foray into the xslt world in several years, so have a deep look. The tests are passing though.

### CODE REVIEW

**Comment by josteinaj** [comment]
LGTM, but I haven't tested it.

@rdeltour feel free to reassign this to me if you're busy. I've started looking through PRs in the three core module repos already and can add this on my TODO as well.

**Comment by capitancambio** [comment]
@rdeltour is in Prague, so he told me to reassign it.
cheers!

**Comment by capitancambio** [comment]
hello guys! shall we merge this pr? I think this pr is a bit stale by now :rofl:

**Comment by bertfrees** [comment]
Hi Javi! Yes we should. Thanks for reminding. I will look a bit closer at the XSLT code.

**Comment by bertfrees** [comment]
I tebased this branch and tested it on the largest DTBook I could find on my computer. It increases the speed a lot indeed. I hope it will improve the issue https://github.com/daisy/pipeline/issues/207.

**Comment by bertfrees** [comment]
Merged in 3b450e3

**Pull request closed without merging**
