### PR TITLE
dtbook to rtf

### PR DESCRIPTION
**Pull request by YLBrailleNet**

### CODE REVIEW

**Comment by bertfrees** [comment]
@YLBrailleNet I've finally reviewed your PR. It looked very good! I have added a few minor fixes, and added a XProcSpec test. The only other remark I have is that the "author" section only contains your name, but not the original author(s) of the Pipeline 1 script. Could you please add them?

**Comment by YLBrailleNet** [comment]
@bertfrees  thanks for the remarks, i'll add that immediately.

**Comment by bertfrees** [comment]
Thanks. Oh and maybe a bit of explanation in the code for why the `doc()` function is being used?

**Comment by bertfrees** [comment]
@YLBrailleNet Is there some documentation for this script in Pipeline 1?

**Comment by bertfrees** [comment]
Merged in fc36ae398dd0d620d267b760c54a359e8065d345
 
See also
- https://github.com/daisy/pipeline-assembly/commit/e3304a0f7c
- https://github.com/daisy/pipeline/commit/bd916da405

**Pull request closed without merging**
